# Generated by Django 6.0.3 on 2026-04-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='is_lion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detection',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='detection',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
