# Generated by Django 6.0.3 on 2026-04-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_detection_is_lion_detection_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drone_name', models.CharField(max_length=100)),
                ('max_speed', models.IntegerField(default=50)),
                ('auto_patrol', models.BooleanField(default=True)),
                ('confidence', models.IntegerField(default=70)),
                ('alert_enabled', models.BooleanField(default=True)),
                ('save_images', models.BooleanField(default=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('refresh_rate', models.IntegerField(default=2)),
            ],
        ),
    ]
