# Generated by Django 6.0.3 on 2026-04-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_systemsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='image',
            field=models.ImageField(null=True, upload_to='detections/images'),
        ),
    ]
