# Generated by Django 6.0.3 on 2026-06-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0004_alter_detection_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RobotTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('robot_online', models.BooleanField(default=False)),
                ('current_zone', models.CharField(default='Unknown', max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='detection',
            name='label',
        ),
        migrations.AlterField(
            model_name='detection',
            name='confidence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='detections/images'),
        ),
    ]
